trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  major: 0
  minor: 0
  patch: $[counter(variables['minor'], 1)]
  buildConfiguration: 'Release'
  project: 'providers/eventStore/Uneventful.EventStore.Cosmos/Uneventful.EventStore.Cosmos.csproj'

steps:

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: 'pack'
      packagesToPack: '$(project)'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: $(major)
      minorVersion: $(minor)
      patchVersion: $(patch)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'