trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectName: 'Uneventful.EventStore/Uneventful.EventStore.csproj'

steps:
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: 'src/Uneventful.EventStore/Uneventful.EventStore.csproj'
#    arguments: '--configuration $(buildConfiguration)'
#    workingDirectory: $(System.DefaultWorkingDirectory)

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/Uneventful.EventStore/Uneventful.EventStore.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'