trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  major: 0
  minor: $[counter(variables['major'], 0)]
  patch: $[counter(variables['minor'], 1)]
  buildConfiguration: 'Release'
  project: 'src/Uneventful.EventStore/Uneventful.EventStore.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: $(major)
    minorVersion: $(minor)
    patchVersion: $(patch)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'